version: "3"

networks:
  project_net:
    driver: bridge

services:
  nginx:
    container_name: project-nginx
    image: nginx:1.23
    networks:
      - project_net
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/run_nginx.sh:/opt/nginx/run_nginx.sh
    ports:
      - ${WEB_PORT}:80
    environment:
      - NGINX_PORT=80
      - APP_SERVICE=project-app
      - APP_PORT=5000
    command: /bin/bash -c /opt/nginx/run_nginx.sh
    depends_on:
      - app

  app:
    container_name: project-app
    image: project_app:${VERSION}
    build:
      context: app/
      dockerfile: Dockerfile
    networks:
      - project_net
    ports:
      - ${APP_PORT}:5000
    environment:
      - VERSION=${VERSION}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SERVER=project-db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./db/:/opt/project/db/
    command: /bin/bash -c "./wait-for-mysql.sh db 3306 && ./migrate.sh /opt/project/db/migrations/ && python app.py"
    depends_on:
      - db

  db:
    container_name: project-db
    image: mysql:8.0
    networks:
      - project_net
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - LANG=ko_KR.UTF-8
    volumes:
      - ./db/data/:/var/lib/mysql
