version: "3"

networks:
  project_net:
    driver: bridge

services:
  nginx:
    container_name: project-nginx
    image: nginx:1.17
    networks:
      - project_net
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/run_nginx.sh:/opt/nginx/run_nginx.sh
    ports:
      - ${WEB_PORT}:80
    environment:
      - NGINX_PORT=80
      - APP_SERVICE=project-app
      - APP_PORT=5000
    command: /bin/bash -c /opt/nginx/run_nginx.sh
    depends_on:
      - app

  app:
    container_name: project-app
    image: project_app:0.3
    build:
      context: app/
      dockerfile: Dockerfile
    networks:
      - project_net
    ports:
      - ${APP_PORT}:5000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SERVER=project-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./db/:/opt/project/db/
    command: /bin/bash -c "./wait-for-postgres.sh db 5432 && ./migrate.sh /opt/project/db/migrations/ && python app.py"
    depends_on:
      - db

  db:
    container_name: project-db
    image: postgres:12.3
    networks:
      - project_net
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
