version: "3"

networks:
  mobilian_net:
    driver: bridge

services:
  nginx:
    container_name: mobilian-nginx
    image: nginx:1.17
    networks:
      - mobilian_net
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/run_nginx.sh:/opt/nginx/run_nginx.sh
    ports:
      - ${WEB_PORT}:80
    environment:
      - NGINX_PORT=80
      - APP_SERVICE=mobilian-app
      - APP_PORT=5000
    command: /bin/bash -c /opt/nginx/run_nginx.sh
    depends_on:
      - app

  app:
    container_name: mobilian-app
    image: mobilian_app:0.2
    build:
      context: app/
      dockerfile: Dockerfile
    networks:
      - mobilian_net
    ports:
      - ${APP_PORT}:5000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_SERVER=mobilian-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app/static/:/opt/mobilian/app/static/
      - ./db/:/opt/mobilian/db/
    command: /bin/bash -c "./wait-for-postgres.sh db 5432 && ./migrate.sh /opt/mobilian/db/migrations/ && python app.py"
    depends_on:
      - db

  db:
    container_name: mobilian-db
    image: postgres:12.3
    networks:
      - mobilian_net
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
